name = "ziku"
version = "0.1.0"
defaultTargets = ["ziku"]
testDriver = "golden-test"

[[lean_lib]]
name = "Ziku"

[[lean_exe]]
name = "ziku"
root = "Main"

[[lean_exe]]
name = "golden-test"
root = "tests.GoldenTest"
